### ISSUE TITLE
`DICTIONARY` fails to load from a saved scene properly.

### ISSUE THREAD

**Issue by ThatRedox** [aTom3333/chunky-octree-plugin#2]
Load a new scene and save:
![image](https://user-images.githubusercontent.com/42661490/184523220-c1208910-1a29-4ab6-9728-08c67b676b66.png)
Restart `Chunky` and open the scene:
![image](https://user-images.githubusercontent.com/42661490/184523232-dbd7d562-2af5-4ee8-a7a9-03f3599eae8a.png)

Using version 0.7.2.
Dosen't appear to have any errors in the logs:
```
Loading render dump: [..]
Render dump loaded: default_2022-08-13_21-59-57.dump
Loading octree default_2022-08-13_21-59-57.octree2
Loading octree (DICTIONARY)
Loading octree (DICTIONARY)
Octree loaded
Built SAH_MA BVH with depth 8
```

**Comment by jackjt8** [comment]
Do you still have this scene/world on hand?

At least during my testing I have not been able to reproduce this when comparing a 1.10 world and a 1.19 extended world while testing packed, dictionary, and dag_tree

**Comment by ThatRedox** [comment]
[DictOctreeTest.zip](https://github.com/aTom3333/chunky-octree-plugin/files/9802720/DictOctreeTest.zip)
Here is the scene loaded with `PACKED`. If you edit the JSON and switch it to `DICTIONARY` the floor will disappear. The original world is also in there.

**Comment by jackjt8** [comment]
Can confirm this bug. Double checked and this is certainly a dictionary only bug that does not appear to impact more "typical" scenes- ie Broville, Greenfield, standard world gen, worldpainter, etc.

You can even create a new `DICTIONARY` scene and after saving a loading you will having the floor missing.

![image](https://user-images.githubusercontent.com/3740917/196445175-427ed24c-9322-444f-bd1f-c41c4d15c14a.png)

![image](https://user-images.githubusercontent.com/3740917/196445082-f1700344-0be2-4268-b8df-4d1580fec254.png)

---

`Load selected chunks` and `Reload chunks` of course "fixes" this issue.. but this is not exactly a valid solution for an in-progress render.

---

Important notes regarding this bug:

![image](https://user-images.githubusercontent.com/3740917/196447988-da7dacde-45f5-41bf-b164-3bfea6909fa4.png)

![image](https://user-images.githubusercontent.com/3740917/196446486-6a8f8218-5138-49ea-8998-e0500705f051.png)

- The area selected does not contain water and contains void.

- A debug world works fine 
![image](https://user-images.githubusercontent.com/3740917/196448817-07b53181-afb2-40fb-bacd-2a37a76522ed.png)

- A superflat world works fine
![image](https://user-images.githubusercontent.com/3740917/196449069-ddbd79d5-a9f7-4acb-87ea-d44e69734ab6.png)

---

I'm not sure what, regarding the world within DictOctreeTest.zip, is causing this issue.

**Comment by aTom3333** [comment]
Thanks for the report (and sorry for the delay, I must have missed the notification back in august).
I've just fixed the bug. (The issue was that the 2*2*2 group at index 0 in the dictionary array was replaced by air because the 0, for the dict index, in the tree data array was interpreted as an air node)
