### ISSUE TITLE
Plugin fails to load on snapshot: `Caused by: java.lang.ClassNotFoundException: se.llbit.chunky.block.UnknownBlock`

### ISSUE THREAD

**Issue by Peregrine05** [aTom3333/chunky-octree-plugin#3]
This is a result of chunky-dev/chunky#1572.

**Comment by PainOchoco** [comment]
Same issue here!

**Comment by leMaik** [comment]
Fixed in [v0.7.4](https://github.com/aTom3333/chunky-octree-plugin/releases/tag/v0.7.4), this issue can be closed.
